# Generated by Django 4.0 on 2023-01-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_td', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Требование',
                'verbose_name_plural': 'Требования',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('code', models.CharField(db_index=True, max_length=15, verbose_name='Код по ГК')),
            ],
            options={
                'verbose_name': 'ЗИП',
                'verbose_name_plural': 'ЗИП',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storages.order', verbose_name='Требование')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storages.part', verbose_name='ЗИП')),
            ],
            options={
                'verbose_name': 'Пункты требования',
                'verbose_name_plural': 'Пункты требований',
            },
        ),
    ]
